### PR TITLE
FIX empty payload raises exception

### LINKED ISSUE #66: empty device post results in a JS error
if a post from a device like

http://130.206.121.52:7896/iot/d?k=TEF&i=restaurant-sensor-0115206c51f60b48b77e4c937835795c33bb953f 

has an empty UL20 payload it results in

{
  "name": "TypeError",
  "message": "Cannot call method 'split' of undefined"
}

it should provide another kind of error or even no error.

### PR DESCRIPTION
**Pull request by dmoranj**
Fixes #66

### CODE REVIEW

File: config.js [hunk 1]
```diff
@@ -77,12 +77,12 @@ config.iota = {
         /**
          * Host where the Context Broker is located.
          */
-        host: 'localhost',
+        host: '52.37.157.18',
```
Comment (AlvaroVega) [inline config.js]: a fix IP in a config?

**Comment by AlvaroVega** [comment]
LGTM
